# Generated by Django 3.1.4 on 2021-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('Post_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('describe', models.CharField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField()),
                ('createDate', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
