# Generated by Django 3.1.4 on 2021-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='url_name',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
