# Generated by Django 3.1.4 on 2021-04-06 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_posts_url_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Post_id',
            new_name='post_id',
        ),
    ]
