# Generated by Django 3.1.4 on 2021-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_posts_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
