# Generated by Django 3.1.4 on 2021-04-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=30)),
                ('recipients', models.CharField(max_length=100)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
                ('sentDate', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
