# Generated by Django 3.1.4 on 2021-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_account',
            name='image',
            field=models.ImageField(null=True, upload_to='image/sponsor'),
        ),
    ]
