# Generated by Django 3.1.4 on 2021-04-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor', '0002_info_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sponsor.info_account'),
            preserve_default=False,
        ),
    ]
