# Generated by Django 3.1.7 on 2021-04-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Live',
            fields=[
                ('contact_live_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=255)),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_User',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_person', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('createDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
