# Generated by Django 3.1.7 on 2021-04-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_live',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact_user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
