# Generated by Django 3.1.4 on 2021-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('about', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='image/course')),
                ('dateCreate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
