# Generated by Django 3.1.4 on 2021-03-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
