# Generated by Django 3.1.4 on 2021-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_banner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
