# Generated by Django 3.1.4 on 2021-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_banner_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
