# Generated by Django 3.1.4 on 2021-03-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('createDate', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
