# Generated by Django 3.1.4 on 2021-03-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subjects', '0002_auto_20210329_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='image/lesson')),
                ('time', models.CharField(max_length=20, null=True)),
                ('views', models.IntegerField(default=0)),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjects')),
            ],
        ),
    ]
