# Generated by Django 3.1.4 on 2021-03-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0004_auto_20210329_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
