# Generated by Django 3.1.4 on 2021-04-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson', '0007_auto_20210401_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.TextField(),
        ),
    ]
