# Generated by Django 3.1.4 on 2021-03-25 09:24

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/image/course'), upload_to='')),
                ('dateCreate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects_Children',
            fields=[
                ('sub_chil_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('totalVisits', models.IntegerField(default=0)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subjects.subjects')),
            ],
        ),
    ]
