# Generated by Django 3.1.4 on 2021-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
