# Generated by Django 3.1.7 on 2021-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('userName', models.CharField(max_length=50, null=True)),
                ('sex', models.BooleanField(null=True)),
                ('point', models.IntegerField(default=0)),
                ('dateCreate', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('activeCount', models.IntegerField(null=True)),
            ],
        ),
    ]
