# Generated by Django 3.1.4 on 2021-03-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dateCreate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
